services:
  postgres:
    image: postgres:16
    container_name: telcocredit-postgres
    environment:
      POSTGRES_USER: telcocredit
      POSTGRES_PASSWORD: telcocredit
      POSTGRES_DB: telcocredit
    ports:
      - "5432:5432"
    volumes:
      - telcocredit_pg:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: telcocredit-redis
    ports:
      - "6379:6379"
    volumes:
      - telcocredit_redis:/data

volumes:
  telcocredit_pg:
  telcocredit_redis:
